Azure/ms-rest-js

index.html
package-lock.json
package.json
test/userAgentFilterTests.ts
webpack.testconfig.ts

Hopefully will be of use.
For now no CI step--you should `npm run build:browser && npm run test:chrome-unit` in the simple case. It's not that fast, but maybe will refine it later.

Browser tests

---

.scripts/publish.js
package-lock.json
package.json

Copied from https://github.com/Azure/perks.extension

Add publish scripts

---

lib/axiosHttpClient.ts
test/node/startTestServer.node.ts
test/shared/axiosHttpClientTests.ts
testserver/index.ts

Resolves #89 (hopefully, if I'm understanding the problem correctly)

Don't overwrite cookie if already present on request

---

lib/credentials/basicAuthenticationCredentials.ts
lib/serializer.ts
lib/util/base64.ts
package-lock.json
package.json
test/shared/credentialTests.ts
test/shared/serializationTests.ts
testserver/index.ts
webpack.config.ts
webpack.testconfig.ts

This is bringing back work done in the past, maybe done on the httpPipeline branch and forgotten. This should save about 20KB when bundling for the browser. I believe there might be corresponding work to do in the generator.

Remove usages of Buffer

---

lib/serializer.ts
lib/serviceClient.ts
test/shared/serializationTests.ts
test/shared/serviceClientTests.ts

Part of the solution Azure/autorest.typescript#167

Support headerCollectionPrefix

---

lib/operationResponse.ts
lib/operationSpec.ts
lib/policies/exponentialRetryPolicy.ts
lib/policies/redirectPolicy.ts
lib/policies/serializationPolicy.ts
package.json
test/shared/serviceClientTests.ts

Resolves https://github.com/Azure/ms-rest-js/issues/97 (partially).

Move error deserialization into serializationPolicy

---

package-lock.json
package.json

I forgot to bump the minor version in my previous PR.

Bump the minor version

---

package.json

I'm just really sloppy today. Sorry.

Fix the main property in package.json

---

lib/policies/serializationPolicy.ts
lib/serviceClient.ts
package-lock.json
package.json
test/shared/serviceClientTests.ts

Resolves https://github.com/Azure/ms-rest-js/issues/97.
This also removes the HttpRequest parameter from the sendOperationRequest() method.

Move successful response deserialization to runtime

---

lib/msRest.ts
lib/policies/deserializationPolicy.ts
lib/serviceClient.ts
package-lock.json
package.json
test/shared/policies/deserializationPolicyTests.ts

Resolves https://github.com/Azure/autorest.typescript/issues/165.

Move request body serialization into ServiceClient.sendOperationRequest()

---

lib/operationArguments.ts
lib/webResource.ts

Avoid use of AbortSignal in public APIs

---

lib/serializer.ts
test/shared/serializationTests.ts

Support x-nullable

---

lib/serviceClient.ts
lib/util/utils.ts
package-lock.json
test/shared/serviceClientTests.ts

Fixes https://github.com/Azure/azure-sdk-for-node/issues/3071.

Fix bug where we were stringifying XML stream request bodies

---

lib/credentials/apiKeyCredentials.ts
lib/credentials/basicAuthenticationCredentials.ts
lib/credentials/tokenCredentials.ts
lib/httpClient.ts
lib/httpOperationResponse.ts
lib/httpPipelineLogger.ts
lib/operationArguments.ts
lib/operationResponse.ts
lib/operationSpec.ts
lib/policies/exponentialRetryPolicy.ts
lib/policies/logPolicy.ts
lib/policies/redirectPolicy.ts
lib/policies/requestPolicy.ts
lib/policies/rpRegistrationPolicy.ts
lib/restError.ts
lib/serializer.ts
lib/serviceClient.ts
lib/util/utils.ts
lib/webResource.ts

Resolves https://github.com/Azure/ms-rest-js/issues/20.

Restructure some of documentation comments

---

lib/serviceClient.ts
package.json
test/shared/serviceClientTests.ts

Resolves https://github.com/Azure/autorest.typescript/issues/189.

Get client properties from ServiceClient instead of OperationArguments

---

lib/msRest.ts
lib/operationArguments.ts
lib/serviceClient.ts
package-lock.json
package.json
test/shared/serviceClientTests.ts

Resolves https://github.com/Azure/autorest.typescript/issues/188.

Simplify OperationArguments

---

lib/msRest.ts

Needed for Azure/autorest.typescript#185

Export interfaces from operationParameter.ts

---

Changelog.md
lib/msRest.ts
lib/policies/deserializationPolicy.ts
lib/policies/exponentialRetryPolicy.ts
lib/policies/generateClientRequestIdPolicy.ts
lib/policies/logPolicy.ts
lib/policies/msRestUserAgentPolicy.ts
lib/policies/redirectPolicy.ts
lib/policies/requestPolicy.ts
lib/policies/rpRegistrationPolicy.ts
lib/policies/signingPolicy.ts
lib/policies/systemErrorRetryPolicy.ts
lib/serviceClient.ts
package.json
samples/node-sample.ts
test/shared/policies/deserializationPolicyTests.ts
test/shared/serviceClientTests.ts

Will need to do fix tests on autorest.typescript, do a version bump in ms-rest-azure-js, and do a version bump in ms-rest-nodeauth.

RequestPolicyCreator -> RequestPolicyFactory

---

lib/httpOperationResponse.ts
lib/msRest.ts
package.json

Related to Azure/autorest.typescript#237

Add base HttpResponse

---

.scripts/unit.js
lib/httpOperationResponse.ts
lib/xhrHttpClient.ts
package-lock.json
package.json
test/node/startTestServer.node.ts
test/shared/defaultHttpClientTests.ts

Typescript 3

---

lib/axiosHttpClient.ts
lib/httpHeaders.ts
lib/xhrHttpClient.ts
test/browser/stub.browser.ts
test/browser/xhrTests.browser.ts

Headers fix

---

lib/operationSpec.ts
lib/serviceClient.ts

Resolves https://github.com/Azure/ms-rest-js/issues/197

Change OperationSpec to be read only

---

package-lock.json
package.json

I really should've bumped the minor version in my previous pull request.

Bump minor version due to LRO changes

---

test/shared/defaultHttpClientTests.ts

Updates the test to benefit from #220

Check instanceof RestError in test

---

lib/axiosHttpClient.ts
lib/util/utils.ts
test/browser/xhrTests.browser.ts
test/node/userAgentFilterTests.node.ts
test/shared/credentialTests.ts
test/shared/defaultHttpClientTests.ts
test/shared/logFilterTests.ts
test/shared/operationParameterTests.ts
test/shared/policies/deserializationPolicyTests.ts
test/shared/serializationTests.ts
test/shared/serviceClientTests.ts
test/shared/urlTests.ts
test/shared/xmlTests.ts
testserver/index.ts
tsconfig.json

Es interop

---

lib/serviceClient.ts
lib/url.ts
test/shared/urlTests.ts

Resolves https://github.com/Azure/ms-rest-js/issues/236.

Add URLBuilder.appendPath()

---

package-lock.json
package.json

fixes https://github.com/Azure/ms-rest-js/issues/241

move @types to devDependencies

---

.scripts/dependencies.ts
.scripts/latest.ts
.scripts/local.ts
.scripts/preview.ts

Resolves https://github.com/Azure/ms-rest-js/issues/246.

Remove script step that changes package.json main property

---

tslint.json

Closes https://github.com/Azure/ms-rest-js/issues/255

Add 'no-return-await' TSLint rule

---

package.json
rollup.config.js

Resolves https://github.com/Azure/autorest.typescript/issues/389.

Fix rollup browser aliasing

---

lib/serializer.ts
package.json
test/shared/serializationTests.ts

Resolves https://github.com/Azure/ms-rest-js/issues/306.

Fix serialization bug for ie11

---

Changelog.md
lib/serviceClient.ts
lib/util/constants.ts
package.json
test/shared/serviceClientTests.ts

Resolves https://github.com/Azure/ms-rest-js/issues/311.

Allow ServiceClientOptions.userAgent property to be a function

---

.scripts/checkConstantsVersion.ts
.scripts/checkEverything.ts
azure-pipelines.yml
lib/serviceClient.ts
lib/util/constants.ts
package.json
test/shared/serviceClientTests.ts

Resolves https://github.com/Azure/ms-rest-js/issues/309.

Allow ServiceClientOptions.requestPolicyFactories to be a function

---

lib/policies/proxyPolicy.browser.ts
lib/util/constants.ts
package.json
rollup.config.ts
test/msAssert.ts
test/msRestUserAgentPolicyTests.ts
test/policies/proxyPolicyTests.ts
webpack.testconfig.ts

Should fix https://github.com/Azure/ms-rest-js/pull/326

Fix including proxy policy in browser

---

lib/axiosHttpClient.ts
lib/util/constants.ts
package.json
test/axiosHttpClientTests.node.ts

Fix http over https bug

---

Changelog.md
lib/serviceClient.ts
lib/util/constants.ts
package.json
test/serviceClientTests.ts

Related to [Issue: 4244](https://github.com/Azure/azure-sdk-for-js/issues/4244) && [PR: 8377](https://github.com/Azure/azure-sdk-for-js/pull/8377)
@ramya-rao-a Please review and approve

Encode query parameters in an array before joining them

---

Changelog.md
lib/serviceClient.ts
test/serviceClientTests.ts

The reason for this PR has been explained in detail in the gist https://gist.github.com/sarangan12/ddcec9a5789984dba777713855634166. 
@joheredi Please review and approve
@ramya-rao-a FYI.....

Code change to check if delimiter is tabs-spaces & value is null/undefined

---

.devops/azure-pipelines-pr.yml
Changelog.md
lib/util/constants.ts
package-lock.json
package.json

Axios has recently fixed a vulnerability. This upgrade makes sure that the safe version of axios is used.

build(deps): updates axios

---

.github/CODEOWNERS
README.md
samples/index.html
samples/node-sample.ts

Some changes are ported from core-http.
Addresses #399

Update sample instructions

---

Changelog.md
lib/util/constants.ts
package.json

- combine changes into one unpublished version
- update changelog

Prepare for 2.2.1 release

---

Changelog.md
lib/url.ts
lib/util/constants.ts
package.json
test/urlTests.ts

port fix from https://github.com/Azure/azure-sdk-for-js/pull/9245. Fixes https://github.com/Azure/ms-rest-js/issues/427.

port fix from https://github.com/Azure/azure-sdk-for-js/pull/9245

---

Changelog.md
lib/util/constants.ts
package-lock.json
package.json

Move @azure/core-auth to dependencies

---

Changelog.md
lib/policies/proxyPolicy.ts
lib/util/constants.ts
test/policies/proxyPolicyTests.ts

- NO_PROXY and ALL_PROXY support
- username and password in proxy url string

Port some proxy enhancements from core-http

---

.devops/azure-pipelines-ci.yml
.devops/azure-pipelines-pr.yml
.devops/azure-pipelines-release.yml
.devops/azure-pipelines-test-dependent-projects.yml
.devops/azure-pipelines-test.yml

Update vmImage to use Ubuntu 18.04 as 16.04 has been removed from devops.

Fix build pipelines

---

.devops/azure-pipelines-test-dependent-projects.yml

as testing v4x autorest.typescript requires it.

Install dotnet sdk 2.1

---

Changelog.md
lib/util/constants.ts
lib/util/xml.browser.ts
package.json

to address https://nvd.nist.gov/vuln/detail/CVE-2023-0842

Upgrade dependency `xml2js` version to `^0.5.0`.
