lib/httpRequest.ts
test/shared/httpRequestTests.ts

@RikkiGibson was right. I was definitely having issues with this previously, but I can't seem to reproduce those issues now.

Re-enable string representations of HttpMethod enum values in HttpRequest

---

lib/util/utils.ts
package-lock.json
package.json

This appears to reduce the webpack bundle size from ~245kb -> ~121kb while still passing all the ms-rest-js and autorest.typescript tests.
as an aside, I'm wondering whether it's worth keeping package-lock.json. It seems to create thousands of lines of diff every time it's recreated. Reproducible builds are great--it's just a little frustrating to have to blow this lockfile away so often to get the latest versions of packages. Maybe there's a better way to use npm that doesn't require doing that.

Bump to v0.3.2. Use isomorphic-xml2js.

---

lib/serviceClient.ts
lib/webResource.ts

This is an attempt to simplify the ServiceClient public API. I understand that ServiceClient.sendRequest() has a bit of redundant validation at this point, but as I do more work to push computation into the runtime, this redundancy will go away.

Remove ServiceClient.pipeline() in favor of ServiceClient.sendRequest()

---

Changelog.md
package-lock.json
package.json

I'm getting things ready for Storage to generate TypeScript SDKs, and publishing the runtime so that it's easier for storage to consume it seems like a good idea to me.

Update mocha dependency, update version number to 0.5.0

---

lib/url.ts
test/shared/urlTests.ts

I forgot to add URL substitution functions for updating path and query arguments.

Add the ability to read, modify, and substitute URL queries

---

lib/fetchHttpClient.ts
lib/httpHeaders.ts
lib/httpOperationResponse.ts
lib/msRest.ts
lib/policies/exponentialRetryPolicy.ts
lib/policies/logPolicy.ts
lib/policies/redirectPolicy.ts
lib/policies/rpRegistrationPolicy.ts
lib/restError.ts
lib/util/utils.ts
test/shared/logFilterTests.ts

- Pulls HttpHeaders class as-is from httpPipeline branch
- Simplifies msRest.ts because I found out `export { ... } from "other-module"` is a thing
- Is there a reason for HttpOperationResponse itself to be a class type? Seems like maybe not since any HttpClient implementation can implement the interface with their own class type. If you don't agree I can change the interface I have there to be some "properties" type which is used as a constructor argument.
- Thinking of just providing the HttpOperationResponse directly in the generated code in the streaming case. Any apparent reason to do it differently?

Don't expose fetch types in HttpOperationResponse

---

lib/msRest.ts

I need these types in ms-rest-azure-js tests (and probably in a lot of legitimate end-user scenarios) so I'm exporting them from the main module.

Export HttpHeaders and RequestPolicyCreator

---

lib/axiosHttpClient.ts
lib/msRest.ts
lib/operationArguments.ts
lib/serviceClient.ts
lib/webResource.ts
test/shared/axiosHttpClientTests.ts

Leaving aside the rename/constructor refactor work for now as it's not trivial to unify `constructor()` and `prepare()` and will break people.

Add onUpload/DownloadProgress properties and createOperationArguments

---

package-lock.json
package.json
tsconfig.json

This brings our bundle from 93.2KB -> 81.4KB. Just seemed so easy to add in that I should just do it. Will do the same with ms-rest-azure-js.

Use ImportHelpers setting

---

package.json

This fixes our automated publishing. I don't want to get lost in making VSTS run our Chrome tests properly right now, so I'm changing the publish script to only run the nodejs mocha tests.
See https://github.com/Azure/ms-rest-js/pull/108#issuecomment-393639685
We may want to tweak the publish job to email us on failure or something like that.

Don't run browser tests when publishing

---

lib/axiosHttpClient.ts
lib/policies/msRestUserAgentPolicy.stub.ts
lib/policies/redirectPolicy.ts
lib/util/utils.ts
package-lock.json
package.json
test/testUtils.ts
tsconfig.es.json
webpack.config.ts
webpack.testconfig.ts

- Removes `url-parse` module in favor of our own `URLBuilder` to save a few kBs
- url-parse is about 3.5 kB while URLBuilder is about 7 kB. Is it accurate @daschult that URLBuilder does stuff that url-parse can't?
- Require specifically `uuid/v4` to save a kB
- Disable `process` polyfill to save a kB
- Don't know how to help our users do this in their own webpack config, but it's a small thing and they're likely to have other code that depends on the process polyfill, so not sure if it matters
- Replace `msRestUserAgentPolicy.js` with a stub in browser to save a few kBs
- See the [package-browser-field-spec](https://github.com/defunctzombie/package-browser-field-spec) to understand what I was doing there
- Removes `withCredentials: true` in axios to enable more typical CORS use cases
- …

Remove more stuff

---

lib/operationSpec.ts
lib/policies/serializationPolicy.ts
lib/serviceClient.ts
package.json
test/shared/policies/serializationPolicyTests.ts

The main change here is that each operation group will have its own serializer, so we don't actually put a serializer into the SerializationPolicy. Please let me know what you think about the design and that of the corresponding PR for autorest.typescript.
We should bump the minor version for this.

Support mappers per operation group

---

.npmignore

Needed this line in .npmignore to actually include the es6 build in the package. The only thing that actually gave this away apparently was our bundlesize check failing over in autorest.typescript. Strange.

Include es/ folder in package

---

lib/serializer.ts
lib/url.ts

Fixes #128. An ms-rest-azure PR will probably come for AzureServiceClient.
This brings us to 70.5 kB -> 68.2 kB because the minifier is allowed to mangle the names of the module-scoped functions instead of having to preserve the names of private members.
I didn't bother to change UrlBuilder to make `private set()` a module-scoped function because it's a very short name :+1: and it also requires changing the private fields referenced by the function to being public

Private functions to closures

---

lib/msRest.ts

We must have forgotten to do this--this prevents external users from making convenient use of BaseRequestPolicy.

Export RequestPolicyOptions

---

lib/queryCollectionFormat.ts
lib/serviceClient.ts
lib/url.ts
tsconfig.json

Fixes #127
This is not really a must have. This saves about 1 kB in the runtime and saves some space in generated code (based on using e.g. `","` instead of `QueryCollectionFormat.Csv`.
If we do this we have to be careful that we only declare `const enums` which we don't expect JavaScript users to want to access in their own code. Based on that idea, I think `QueryCollectionFormat` is a good candidate for `const` while `HttpPipelineLogLevel` should not be `const`.

Use const enums where possible

---

lib/queryCollectionFormat.ts

It seems like it's too easy for const enums exposed at the library level to cause runtime errors at the usage site, so I'm reverting the `const` change for this enum. If we are in some position of desperately wanting to shave bytes off our bundles then we can consider changing this to something smaller.

Make QueryCollectionFormat non-const

---

lib/serializer.ts
lib/serviceClient.ts
package.json

This leverages the tagged unions feature to improve the type safety and maintainability of the Mapper interfaces. It solves an issue where the new headerCollectionPrefix failed to type check, and removes the `[key: string]: any` index signature that made us work around variance in the `type` property of various mappers by essentially not type checking them.

Improve type safety of mappers

---

lib/axiosHttpClient.ts
lib/defaultHttpClient.browser.ts
lib/defaultHttpClient.ts
lib/msRest.ts
lib/policies/serializationPolicy.ts
lib/serviceClient.ts
lib/xhrHttpClient.ts
package.json
test/shared/axiosHttpClientTests.ts
test/shared/defaultHttpClientTests.ts
test/shared/policies/serializationPolicyTests.ts
testserver/index.ts
webpack.config.ts
webpack.testconfig.ts

Fixes #138 by moving JSON/XML parsing to the serializationPolicy. This should also make possible to add variants of serializationPolicy which handle either only JSON or both JSON and XML, which should save our JSON-only users another 6 kB.
This brings our bundle size from 67 kB -> 53.5 kB.

Use XhrHttpClient in browser

---

lib/serviceClient.ts

This fixes the broken test in Azure/autorest.typescript#181
So now, we basically have the following precedence, where higher is.. well, higher:
1. contentType mapper property
2. operation header parameter
3. custom header

Allow operation headers and custom headers to override contentType

---

lib/operationSpec.ts
lib/serviceClient.ts

Resolves https://github.com/Azure/autorest.typescript/issues/111.
These are the necessary changes in the runtime to move OperationSpecs out of the functions that use them.

Make OperationSpec.baseUrl an optional property for moving OperationSpecs into module/file scope

---

lib/serviceClient.ts
lib/webResource.ts
lib/xhrHttpClient.ts
package.json
test/shared/defaultHttpClientTests.ts
test/shared/logFilterTests.ts
test/shared/serviceClientTests.ts

Closes #162
Continuation of #161
- `withCredentials` will be provided in the `ServiceClientOptions`-- we assume that this is held in common for all requests made with a client, just like the credentials itself. We maybe could do some tricky inference to decide "oh, we have credentials, and this request is cross origin, so let's try and do the right thing"--but this seems good enough.
- Removing the unused `requestInit` property which is a breaking change

Allow withCredentials: true

---

lib/serializer.ts

This is related to Azure/autorest.typescript#193.
The generator will automatically lowercase the serializedName of each property in a headers mapper, which we rely on for case-insensitive headers deserialization. It's also kinda redundant to emit the xmlName if it's identical to the serializedName.
This lets us get the correct behavior for headers more easily and saves a bit of space. Having xmlName at all instead of just serializedName in the mapper seems a bit smelly--but not going to try and track that down right now..

Fall back to serializedName when deserializing property in XML mode

---

lib/msRest.ts
lib/util/utils.ts
test/shared/utilsTests.ts

Resolves https://github.com/Azure/autorest.typescript/issues/192.
responseToBody enables a much more compact implementation of the body overloads in generated code.
Before:
```ts
getValid(options?: msRest.RequestOptionsBase, callback?: msRest.ServiceCallback<Models.Basic>): any {
if (!callback && typeof options === 'function') {
callback = options;
options = undefined;
}
let cb = callback as msRest.ServiceCallback<Models.Basic>;
if (!callback) {
return this.getValidWithHttpOperationResponse(options).then((operationRes: msRest.HttpOperationResponse) => {
return Promise.resolve(operationRes.parsedBody as Models.Basic);
}).catch((err: Error) => {
return Promise.reject(err);
});
} else {
msRest.promiseToCallback(this.getValidWithHttpOperationResponse(options))((err: Error, data: …
```

Add responseToBody method

---

lib/axiosHttpClient.ts
package-lock.json
package.json
test/shared/defaultHttpClientTests.ts
webpack.testconfig.ts

Fixes #168
This strives for an as-uniform-as-possible experience between nodejs and browser. The progress callbacks will be called for both stream and buffer/string arguments--it's just (I assume) there will only be one progress event in the buffer case.

Call progress callbacks in nodejs streams

---

lib/msRest.ts
lib/operationParameter.ts
lib/serializer.ts
lib/serviceClient.ts
package.json
test/shared/operationParameterTests.ts
test/shared/serializationTests.ts
test/shared/serviceClientTests.ts

It seems that the way we were defining the mapper interfaces was more or less causing us to lose out on some type safety the whole time.
- Our tests often elided serializedName in Sequence mappers, even though it's supposed to be a required property. Therefore I just decided to make serializedName an optional property.
- className and modelProperties were both expected to be present on CompositeMapper even though it only really makes sense to provide exactly one of those properties
I basically made some tweaks that somehow is causing TypeScript now to have the desired strictness about our mappers, and also give us a path toward removing some redundant mapper properties--but it'll also require minor generator changes to make the gen code now compile, so I'm bumping the minor version here.

Mapper interfaces

---

package.json

When bundling a sample I found this flag prevented webpack from including a redundant copy of the runtime in the bundle.

Add "sideEffects": false for webpack 4

---

lib/msRest.ts

I would really like if we could run some static analysis to ensure that all the types referenced in our exported types also get exported.. I can't think of a case where I'd want to hide a type declaration for something I'm using as e.g. a property type on a class.
@XiaoningLiu

Export AbortSignalLike

---

lib/msRest.ts
lib/policies/deserializationPolicy.ts
lib/serviceClient.ts
lib/util/utils.ts
lib/util/xml.browser.ts
lib/util/xml.ts
package-lock.json
package.json
webpack.config.ts
webpack.testconfig.ts

Drops isomorphic-xml2js and uses a simplified implementation with no runtime configuration supported. Saves 4 KB--now the overhead all users have to take on for XML support is just 2 KB.
Passes autorest.typescript tests.

Browser xml

---

lib/axiosHttpClient.ts
lib/webResource.ts
lib/xhrHttpClient.ts

Resolves #183. See that issue for context.
This is a pretty minor breaking change and autorest.typescript had no dependency on the property. So I'm tempted to just merge this without bumping the package version while we are still before preview of our auto-generated SDKs.

Remove totalBytes property from TransferProgressEvent

---

lib/serviceClient.ts
test/shared/serviceClientTests.ts

This prevents the _response from showing up in JSON.stringify, Object.keys(), console.log, etc. while still being accessible if you actually `res._response`.
I think this reduces clutter. But chime in and let me know what you think.

Use Object.defineProperty for _response property

---

lib/serviceClient.ts

I found that the flattened responses didn't work right for paging because we already do something tricky in the serializer to convert e.g. the `{ "value": [...], nextLink: "..." }` into an array with a nextLink property.
This change more or less anticipates what the serializer is doing and carries on to produce an array with the additional properties assigned to it.
There's also a fix that needs to be made in the generator--PR will land soon.

Correctly interpret paged responses as arrays

---

lib/xhrHttpClient.ts
test/shared/defaultHttpClientTests.ts
testserver/index.ts

Fixes an IE 11-specific issue reported by @XiaoningLiu where `xhr.send(undefined)` would result in the body content `undefined` going over the wire.

Fix for IE 11 undefined body

---

lib/serviceClient.ts
test/shared/serviceClientTests.ts

Node 6 doesn't support Object.values so changing it. Reported by @XiaoningLiu.

Change Object.values to Object.keys

---

lib/serializer.ts
test/shared/serializationTests.ts

We don't have back compat concerns so removing `getPolymorphicMapperStringVersion` and simplifying the remaining code. The errors given could maybe be better, or even removed if we want to assume mappers are always well-formed. We don't have tests that exercise the errors as far as I know.
53 KB -> 52.2 KB fwiw.

Simplify polymorphic serialization

---

lib/serializer.ts

There are test cases where the response contains an unknown or missing discriminator value. This change makes it so any failure to look up a polymorphic mapper results in us simply falling back to the mapper specified for the parameter or return type.
We're now at 52.1 KB.

Tolerate unknown/missing polymorphic discriminators

---

lib/restError.ts

ms-rest-js throws an instance of `RestError` when it encounters HTTP error (4xx, 5xx) but the error turns out as an instance of `Error` while transpiling to ES5. It makes difficult to distinguish between a validation error (an instance of `Error`) and a REST error (an instance of `RestError` on TypeScript code, but this will be turned out as an instance of `Error` on the current implementation).
This pull request changes lib/restError.ts to follow [recommendation of TypeScript wiki](https://github.com/Microsoft/TypeScript-wiki/blob/master/Breaking-Changes.md#extending-built-ins-like-error-array-and-map-may-no-longer-work). This change allows you to use `instanceof RestError` on a transpiled code.
see also https://github.com/Azure/autorest.typescript/issues/234 and thanks @RikkiGibson

Fix `instanceof RestError` doens't work

---

lib/util/utils.ts

Mentioned by @XiaoningLiu in https://github.com/Azure/azure-storage-js/pull/11#issuecomment-423432712
This changes a cyclic dependency on the WebResource constructor to just a cyclic dependency on the WebResource interface. TypeScript will stop emitting `import { WebResource } ...` and so rollup should stop complaining.
We are at 52 KB right now, BTW.

Break cyclical reference between utils and webResource

---

Changelog.md
lib/credentials/credentials.ts
lib/msRest.ts
package.json

Changelog's format adjusted to meet requirements of https://github.com/DavidAnson/markdownlint/blob/v0.11.0/doc/Rules.md#md032---lists-should-be-surrounded-by-blank-lines.
> Rationale: Aside from aesthetic reasons, some parsers, including kramdown, will not parse lists that don't have blank lines before and after them.

Add Authenticator type

---

.vscode/launch.json
lib/serializer.ts
test/shared/policies/deserializationPolicyTests.ts

This PR is all about this XML scenario:
```xml
<element attribute="value">text</element>
```
OpenAPI doesn't handle this scenario at all, so in your schema you have to either specify the attributes or the text. If you specify the attributes, then our generator would create a CompositeMapper. If you specify the text property (see the tests for an example), then our serializer was seeing a "StringMapper" but was given a composite object. As such, the serializer would just pass the composite object through unchanged.
This PR changes that so that the body gets passed through.

Ignore XML headers when deserializing XML elements with headers and text

---

Changelog.md
package.json
rollup.config.js

Resolves https://github.com/Azure/ms-rest-js/issues/247.
Ever since we started bundling this package our debugging story has been that you have to write the code in TypeScript, but debug in JavaScript.
I looked around today and found the `rollup-plugin-sourcemaps` package that successfully maps the bundle back to the original TypeScript code. It makes for a much better debugging experience.
I tested this by debugging the unit tests in ms-rest-azure-js against my local copy of ms-rest-js.

Add better sourcemap support for debugging

---

lib/axiosHttpClient.ts
lib/util/constants.ts
package.json

- type from tunnel is exposed but the types dependency is a dev dependency only
- use valid es6 module syntax for 'http' and 'https' packages

Fix tunnel types are missing

---

Changelog.md
lib/axiosHttpClient.ts
lib/util/constants.ts
package.json

`axios` changed the way it treats properties of the request config in `0.19.0`. Previously we were setting `trasnformResponse` to `undefined`. This would indicate `axios` to not transform (`JSON.parse()`) the response body. In `0.19.0`, they are setting the default response transformer if transformResponse is set to `undefined`. This breaks our pasrsing logic where we are doing `JSON.parse()` on `operationResponse.bodyAsText`. Moreover, we are exposing the `bodyAsText` property in the generated clients. 
Not populating this property or setting the value of this property to a parsed JSON would be a breaking change for our users.
Hence we are setting the `transformResponse` property in the request config to an indentity function that returns the response body as-is.

Set tranformResponse property of axios req. config to an identity function

---

Changelog.md
lib/credentials/domainCredentials.ts
lib/msRest.ts
lib/util/constants.ts
package.json

Added a new DomainCredentials class for make it easier to supply EventGrid domain credentials. Event Grid domain is a recently introduced concept/resource and applications can publish events to an EventGrid domain for which an api key needs to be provided, and this newly introduced DomainCredentials class makes it easy to do so.

Added domainCredentials for authentication to EventGrid domains.

---

Changelog.md
lib/serializer.ts
lib/util/constants.ts
package.json
test/data/TestClient/lib/models/mappers.ts
test/serializationTests.ts

- Added support to not send default values while sending the request.
- Added support to populate entities with it's default value if it is present in the mapper while deserializing the response.
- During deserialization, if the service does not provide the **_discriminator_** property then we set it. While setting the _**discriminator**_ property, we compare model property name and the `clientName` of the `polymorphicDiscriminator` instead of the `serializedName` of the `polymorphicDiscriminator`.
- Added tests for serializing and deserializing additional properties.

serialization updates

---

.devops/azure-pipelines-pr.yml
.devops/azure-pipelines-test-dependent-projects.yml

This change fixes an issue that was discovered when PR #370 was created: this repo clones and builds the `autorest.typescript` repo during PR CI runs to verify that no unexpected breaking changes are introduced.  Since `autorest.typescript` v5 (on `master`) has made some API changes regarding credential types, we now need to explicitly clone the `v4x` branch of that repo so that the right interfaces are used.

Clone the v4x branch of autorest.typescript for testing purposes

---

.scripts/unit.ts
Changelog.md
lib/axiosHttpClient.ts
lib/util/constants.ts
package.json
test/defaultHttpClientTests.ts
test/mockHttp.ts

Fixes: #374 
Creating a separate axios instance and moving the interceptor code out of the sendRequest() method.
An interceptor was added to the static axios instance on each sendRequest() call which can lead to out of memory issue if hundreds of requests are made as the added interceptor is not ejected after the request is made.

Out of memory error on making multiple requests

---

Changelog.md
lib/nodeFetchHttpClient.ts
lib/policies/msRestUserAgentPolicy.browser.ts
lib/util/constants.ts
package.json
test/defaultHttpClientTests.ts

fixes #373 
We ran into the same issue as @christiango when using webpack for a server-side node project.

Fix node-fetch require for webpack

---

.devops/azure-pipelines-test-dependent-projects.yml

This change forces the `autorest.typescript` dependent project build to use Node 10 because there's an issue with Gulp when running on Node 12 that causes this error to be thrown after running `npm install`:
```
> @microsoft.azure/autorest.typescript@5.0.2 prepare /home/vsts/work/1/.tmp/autorest.typescript
> gulp install_common && gulp build
fs.js:35
} = primordials;
^
[ReferenceError: primordials is not defined]
```

Use Node 10 when building autorest.typescript to avoid Gulp issue

---

Changelog.md
lib/serviceClient.ts
lib/util/constants.ts
package-lock.json
package.json
test/defaultHttpClientTests.ts
test/serviceClientTests.ts

Issue:
When an operation spec defines that a response should be of type Sequence (array) but the service actually returns null/undefined instead of an empty list, we end up crashing with the following error as the empty response body gets deserialized as {}
```
TypeError: (_response.parsedBody || []).slice is not a function at flattenResponse (/mnt/c/Users/jepri/scratch/node_modules/@azure/ms-rest-js/dist/msRest.node.js:3518:62)
at /mnt/c/Users/jepri/scratch/node_modules/@azure/ms-rest-js/dist/msRest.node.js:3353:47
at at process._tickCallback (internal/process/next_tick.js:189:7)
```
See Azure/azure-sdk-for-js/issues/8445
**Note**:  `[...(_response.parsedBody || [])]` gets compiled into `(_response.parsedBody || []).slice()`.
Fix:
When we are expecting an array, make sure we have one …

[1.x] Make sure parsed body is an array when expecting Sequence

---

Changelog.md
lib/serviceClient.ts
lib/util/constants.ts
test/serviceClientTests.ts

Issue:
When an operation spec defines that a response should be of type Sequence (array) but the service actually returns null/undefined instead of an empty list, we end up crashing with the following error as the empty response body gets deserialized as {}
```
TypeError: (_response.parsedBody || []).slice is not a function at flattenResponse (/mnt/c/Users/jepri/scratch/node_modules/@azure/ms-rest-js/dist/msRest.node.js:3518:62)
at /mnt/c/Users/jepri/scratch/node_modules/@azure/ms-rest-js/dist/msRest.node.js:3353:47
at at process._tickCallback (internal/process/next_tick.js:189:7)
```
See Azure/azure-sdk-for-js/issues/8445
**Note**:  `[...(_response.parsedBody || [])]` gets compiled into `(_response.parsedBody || []).slice()`.
Fix:
When we are expecting an array, make sure we have one …

Make sure parsed body is an array when expecting Sequence

---

Changelog.md
lib/util/constants.ts
package.json

This PR is to fix issue https://github.com/Azure/ms-rest-js/issues/396. The proxyPolicy.browser.js file is not loading correctly even in HTML samples. This PR will fix it. I have tested it with the sample provided in the issue.
@ramya-rao-a Please review and approve.

Code to load proxyPolicy browser js

---

lib/axiosHttpClient.ts
lib/util/constants.ts
lib/webResource.ts
package.json

This port will allow the Bot Framework SDK to better support customer bots with high traffic.
For some more context, the Bot Framework JS SDK currently makes heavy use of the `@azure/ms-rest-js` library. Due to requirements around backwards compatibility, we are tied to the `1.x` branch (currently `v1.8.15`). In particular, we support customization of the underlying Axios HTTP client. In effect, this means that upgrading to the `2.x` version of this library is currently not tenable.
In order to better support customers with high traffic bots running on Azure, we need to leverage HTTP keepalive as much as possible. The `2.x` version of this library added a `keepAlive` setting to the `WebResource` class (though, to be fair, exposing an `agent` parameter directly might be even more …

Port WebResource keepAlive setting from 2.x to 1.x

---

Changelog.md
lib/axiosHttpClient.ts
lib/policies/agentPolicy.browser.ts
lib/policies/agentPolicy.ts
lib/serviceClient.ts
lib/util/constants.ts
lib/webResource.ts
lib/xhrHttpClient.ts
package-lock.json
package.json
test/policies/agentPolicyTests.ts
test/xhrTests.browser.ts
webpack.testconfig.ts

Ports functionality to 1.x from:
https://github.com/Azure/ms-rest-js/pull/403/files

Port HTTP agent ServiceClientOption to 1.x

---

Changelog.md
lib/msRest.ts
lib/nodeFetchHttpClient.ts
lib/policies/agentPolicy.browser.ts
lib/policies/agentPolicy.ts
lib/serviceClient.ts
lib/util/constants.ts
lib/webResource.ts
lib/xhrHttpClient.ts
package.json
test/policies/agentPolicyTests.ts
test/xhrTests.browser.ts
webpack.testconfig.ts

This commit introduces support for passing a custom HTTP and/or HTTPS
agent as a `ServiceClientOption` option, a `WebResource` option, or by
using the `agentPolicy` mechanism. This will provide users greater
control over how outbound requests are made when using this library via
Node.
I intend to port this change back to the `1.x` branch (once it is approved and merged) so the Bot Framework SDK can make use of it. This will help mitigate the issue described in https://github.com/microsoft/botbuilder-js/issues/183.

Add HTTP agent settings and policy

---

lib/util/xml.ts

Currently building master fails with the following error:
```lib/util/xml.ts:8:5 - error TS2345: Argument of type '{ explicitArray: boolean; explicitCharkey: boolean; rootName: string | undefined; renderOpts: { pretty: false; }; }' is not assignable to parameter of type 'BuilderOptions'.
Object literal may only specify known properties, and 'explicitArray' does not exist in type 'BuilderOptions'.
8     explicitArray: false,
~~~~~~~~~~~~~~~~~~~~
Found 1 error.
```
because of new changes in `@types/xml2js`. This PR fixes the issue by removing unnecessary arguments from the builder options that were not used anywhere in the constructor. Tests succeeds locally.

Fix a build error involving xml2js

---

Changelog.md
lib/credentials/azureIdentityTokenCredentialAdapter.ts
lib/credentials/tokenResponse.ts
lib/serviceClient.ts
lib/util/constants.ts
package.json

Enables using identity's TokenCredential using an adapter that converts to `ServiceClientCredentials`.
TODO
- make a release.

Add TokenCredential adapter

---

Changelog.md
lib/credentials/azureIdentityTokenCredentialAdapter.ts
lib/credentials/tokenResponse.ts
lib/serviceClient.ts
lib/util/constants.ts
package-lock.json
package.json

Enables using identity's TokenCredential using an adapter that converts to `ServiceClientCredentials`. Similar to https://github.com/Azure/ms-rest-js/pull/410.

Adding support for @azure/identity in v1

---

Changelog.md
lib/util/constants.ts
package-lock.json
package.json

to avoid pulling in @types/node indirectly.

Move @types/tunnel from depedency to dev dependency

---

.devops/azure-pipelines-test-dependent-projects.yml

`npm run test` didn't surface some build errors

CI should build ms-rest-azure-js after installing ms-rest-js

---

Changelog.md
lib/axiosHttpClient.ts
lib/util/constants.ts
package-lock.json
package.json

by duplicating the interface. `createTunnel()` is only used internally for testing.
Even though we don't exporse it in public API surface, it is causing problem requiring dependent projects to have dev dependency on @types/tunnel.

Stop depending on tunnel.HttpsOverHttpsOptions for createTunnel()

---

Changelog.md
lib/proxyAgent.ts
lib/util/constants.ts
package.json

Porting fix from v1.x branch https://github.com/Azure/ms-rest-js/pull/434

Stop depending on @types/tunnel for createTunnel

---

lib/webResource.ts

Fixes #393. If a simple options object is passed to `sendRequest`, [this code](https://github.com/Azure/ms-rest-js/blob/4208098ab146ad6d37611306c01aac3c93db0941/lib/serviceClient.ts#L227-L238) tries to normalize it into a common `WebResource` object via `WebResource.prepare`. This method does not currently copy in `streamResponseBody` from the options, but it should, so this PR fixes that.

Update WebResource.prepare to also copy streamResponseBody

---

Changelog.md
lib/msRest.ts
lib/util/constants.ts
package.json

The `AzureIdentityCredentialAdapter` allows users of this package to make use of credentials from `@azure/identity`.
When it was added, the plan was to then update the auto generated packages that depend on this package to have a constructor overload that would take the `TokenCredential` interface. As it would take a while to update over 150 packages to have this change, it is beneficial to expose this adapter for folks who may want to make use of it sooner.
Case in point: #445

Expose AzureIdentityCredentialAdapter in the public API

---

Changelog.md
lib/policies/msRestUserAgentPolicy.browser.ts
lib/util/constants.ts
package.json

- Use self instead of window when referring to the global object
- This came up recently in a few cases: https://github.com/Azure/azure-sdk-for-js/issues/11067 and in this discussion: https://github.com/Azure/azure-sdk-for-js/pull/13232#discussion_r557793538
- window is not always the global object, but self's reference changes depending on the context and will point to the right global object
We made this change in azure-sdk-for-js but we should make it here as well.

Use self instead of window when referring to the global object

---

Changelog.md
lib/fetchHttpClient.ts
lib/httpOperationResponse.ts
lib/policies/redirectPolicy.ts
lib/serviceClient.ts
lib/util/constants.ts
lib/webResource.ts
package.json
test/policies/redirectPolicyTests.ts
test/redirectLimitTests.ts

In our usage we want to be able to specify the redirect behaviour for an individual request. I have added the property `redirectLimit` to `RequestPrepareOptions` and `WebResource`. 
It turns out the existing `redirectPolicy` was never executed as the call to node-fetch does not override the default value of redirect='follow'. As it was, node-fetch processed all redirects before the redirectPolicy was executed. I have modified this so that if a redirectLimit is defined, the call to node-fetch will use redirect='manual'
I've also added `url?:string` and `redirected?:boolean` to the response to mimic the behaviour of node fetch. Returning these values seems logical, and in our usage we require them in the response.
I have tried to write some tests that cover the main behavioural changes, but …

Specify redirect behaviour for indivual requests

---

Changelog.md
lib/serializer.ts
lib/util/constants.ts
package.json
test/data/TestClient/lib/models/mappers.ts
test/serializationTests.ts

Copy attributes back post de-serializing array

---

Changelog.md
lib/proxyAgent.ts
lib/util/constants.ts
package.json
test/proxyAgent.node.ts

It turns out that in some enterprise customer the proxy auth settings include a
username, but not a password: microsoft/AzureStorageExplorer#4430
This change allows password-less auth settings to be passed to the underlying agent.
It's unclear whether it's a real scenario when a proxy auth has a password, but
not username so this PR doesn't consider this scenario.

Allow password-less proxySettings

---

Changelog.md
lib/util/constants.ts
lib/util/utils.ts
package.json
rollup.config.ts

From https://github.com/Azure/ms-rest-js/issues/455:
> Currently, installing @azure/ms-rest-js@latest, produces the following message:
> deprecated uuid@3.4.0: Please upgrade to version 7 or higher. Older versions may use Math.random() in certain circumstances, which is known to be problematic. See https://v8.dev/blog/math-random for details.
So this PR upgrades dep on uuid to latest version. Fixes https://github.com/Azure/ms-rest-js/issues/455

Upgrade uuid dependency to v8

---

Changelog.md
lib/credentials/azureIdentityTokenCredentialAdapter.ts
lib/serializer.ts
lib/serviceClient.ts
lib/util/constants.ts
package.json
test/serviceClientTests.ts

Added a new property `baseUri` on the `ServiceClientOptions`, so that when a `TokenCredential` is sent to `ServiceClient`, it now automatically sets the scope of future token requests based on the `options.baseUri` property.
This should address https://github.com/Azure/azure-sdk-for-js/issues/15945

Adds property baseUri on the ServiceClientOptions

---

Changelog.md
lib/util/constants.ts
package.json

update node-fetch to 2.6.7 to fix [CVE-2022-0235](https://snyk.io/vuln/npm:node-fetch)

fix: :arrow_up: CVE-2022-0235

---

package.json

UUID was updated to 8.3.2, but @types/uuid was still using the 3.x version

Match types version of uuid

---

Changelog.md
lib/util/constants.ts
lib/util/xml.browser.ts
lib/util/xml.ts
package.json

porting fix from PR https://github.com/Azure/azure-sdk-for-js/pull/22715
Trusted Types is/are a set of web APIs that give us the ability to control and
restrict data that flows into dangerous DOM APIs in our apps. Main goal of this
mechanism is to prevent successful exploitation of HTML and DOM-based
Cross-Site-Scripting (XSS) vulnerabilities.
https://github.com/w3c/webappsec-trusted-types
Our code does not parse HTML strings. The parsed DOM object is not exposed to
outside world either. This PR adds trusted types policies to make the parsing
code compliant at running time. Consumers of our packages can review and add the
policy to their allowed list.

Address Trusted Types compliance issue

---

Changelog.md
lib/util/constants.ts
lib/util/xml.browser.ts
package.json

In our use-case of the ms-rest-js library, we have a large existing application (complete with caching, service-workers, etc) that we dynamically load additional JavaScript code into. The additional JS is what brings in the ms-rest-js.
The application has Trusted Types enabled (e.g., CSP rule `'trusted-types LibraryA LibraryB etc`). But, interestingly, its `require-trusted-types-for 'script'` is currently under "report only" (`Content-Security-Policy-Report-Only`). In those cases, a call to `trustedTypes.createPolicy` will fail because the policy isn't on the allowed-list, even though _skipping_ the `createPolicy` would be OK. So in effect, https://github.com/Azure/ms-rest-js/commit/531aea9bfbbe6ef6c06984ab06f99775b90923ca introduced a regression.
We are working on extending the …

Wrap trusted-types policy creation in a try/catch

---

package.json

As newer versions contain syntax not recognized by TypeScript v3.9.
It is not straightforward to upgrade TypeScript version because another dev dependency `tslint-eslint-rules` requires TypeScript v3.

Pin the indirect dev dependency `@types/bluebird` version to 3.5.36

---

.devops/azure-pipelines-release.yml

There's some weird webpack error in the release pipeline.  NodeJS v14 worked fine.

Use NodeJS version v14
